services:
  web:
    build:
      context: .
      dockerfile: django-backend/build/Dockerfile
    restart: always
    volumes:
      - ./django-backend:/app
      - static_volume:/app/staticfiles
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./prisma/.env
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - app_network

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web
    networks:
      - app_network

  chainlit:
    build:
      context: .
      dockerfile: chainlit/build/Dockerfile
    restart: always
    volumes:
      - ./chainlit:/app
    command: ["uv", "run", "chainlit", "run", "main.py", "--host", "0.0.0.0", "--port", "8000", "-h", "-w"]
    depends_on:
      - postgres
    networks:
      - app_network
    ports:
      - "8000:8000"

networks:
  app_network:

volumes:
  postgres-data:
  static_volume: