services:
  web:
    build:
      context: .
      dockerfile: django-backend/build/Dockerfile
    restart: always
    volumes:
      - ./django-backend:/app
      - static_volume:/app/staticfiles
    depends_on:
      - postgres
    networks:
      - app_network
    env_file:
      - ./.env

  postgres:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER:-root}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-root}
      - POSTGRES_DB=${DATABASE_NAME:-postgres}
    env_file:
      - ./.env
    ports:
      - ${DATABASE_PORT:-5432}:5432
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web
    networks:
      - app_network

  chainlit:
    build:
      context: .
      dockerfile: chainlit/build/Dockerfile
    restart: always
    volumes:
      - ./chainlit:/app
    command: ["uv", "run", "chainlit", "run", "main.py", "--host", "0.0.0.0", "--port", "8000", "-h", "-w"]
    depends_on:
      - postgres
      - web
      - nginx
    networks:
      - app_network
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - DJANGO_BACKEND_URL=http://nginx

  prisma_cli:
    build:
      context: .
      dockerfile: prisma/build/Dockerfile
    container_name: prisma_cli_service
    working_dir: /app
    volumes:
      - ./prisma:/app/prisma
      - ./.env:/app/.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    stdin_open: true
    tty: true
    command: ["tail", "-f", "/dev/null"]

networks:
  app_network:

volumes:
  postgres-data:
  static_volume: