services:
  web:
    build:
      context: .
      dockerfile: django-backend/build/Dockerfile
    restart: always
    volumes:
      - ./django-backend:/app          
      - static_volume:/app/staticfiles
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - django-backend/build/db.env
    networks:
      - app_network

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web
    networks:
      - app_network

  chainlit:
    build:
      context: .
      dockerfile: chainlit/build/Dockerfile
    restart: always
    volumes:
      - ./chainlit:/app 
    command: ["uv", "run", "chainlit", "run", "main.py", "--host", "0.0.0.0", "--port", "8000", "-h", "-w"]  
    depends_on:
      - db
    networks:
      - app_network
    ports:
      - "8000:8000"

networks:
  app_network:

volumes:
  postgres_data:
  static_volume: 