model_list:
  # OpenAI models
  - model_name: o4-mini
    litellm_params:
      model: openai/o4-mini
      api_key: ${OPENAI_API_KEY}
  - model_name: o3-mini
    litellm_params:
      model: openai/o3-mini
      api_key: ${OPENAI_API_KEY}
  - model_name: gpt-4.1-mini
    litellm_params:
      model: openai/gpt-4.1-mini
      api_key: ${OPENAI_API_KEY}
  - model_name: gpt-4.1-nano
    litellm_params:
      model: openai/gpt-4.1-nano
      api_key: ${OPENAI_API_KEY}
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: ${OPENAI_API_KEY}
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: ${OPENAI_API_KEY}


# Routing settings
router_settings:
  routing_strategy: simple
  timeout: 30
  num_retries: 3

# Cost tracking
cost_tracking:
  enabled: true
  cost_file: ./costs.json
  detailed_view: true

# Usage limits and logging settings
litellm_settings:
  drop_params: true
  success_callback: ["user_tracking"]
  failure_callback: ["user_tracking"]
  database_url: "${LITELLM_DB_URL}"
  set_verbose: false

# Logging
general_settings:
  proxy_logging: false
  verbose: false
  log_level: "ERROR"
